### ISSUE TITLE
videos are not downloading?

### ISSUE THREAD

**Issue by nabeelterafort** [fknives/Android-App-TikTok-Downloader#14] opened 2023-11-24 07:05 UTC
Tiktok videos are not downloading now whats the issue

**Comment by fknives** [comment] 2023-11-24 07:45
Hey, thanks for the interest. As of now the App on my phone still downloads videos.
One thing I noticed however is that if a video was removed from TikTok downloading it will always fail and thus the next video won't be started. 
To check this you can click on the Link in the Downloader app.
If it is indeed the case, you can swipe away the video from the queue.
Otherwise you might also try reordering the video queue by long tapping a card and moving it up or down.

I am planning to do an update which communicates these better.
I hope this helps

**Comment by fknives** [comment] 2023-12-14 21:18
Hmm, clearly existing videos started to fail to download for me too. I will look into it and will create a release

**Comment by fknives** [comment] 2023-12-14 21:51
Hmm, the problem is not fully fixed by the PR.
It fixed one, but looks like sometimes the link throws the user to the login page, I should fix that also if I can. I imagine it is something like captcha.

I think the easiest resolution for that is to:
- Recognize this state
- Show an option to the user for authenticating the downloader app (There is a QR code option which could be used to link directly back to the app)
- Store the auth token and use in subsequent requests.

Unknowns:
- What token needs to be stored and sent
- How to get that token in the first place
- What happens if the token expires, does the same webpage shows or it is a separate issue?
- How to have a test for this case without exposing my own account? Could I create a test account for this reason with secrets?

**Comment by fknives** [comment] 2023-12-22 14:07
NVM I was tried and used the wrong build, #15 fixed the original issue.
The potential issue with videos requiring login bill be tracked #22 and closing this with 1.3.1 release

**Closed as completed by fknives** 2023-12-22 14:07 UTC
Labels: bug, High Priority
